### PR TITLE
Feature/multi agency

### PR DESCRIPTION
**Pull request by am-kantox**
This `PR` adds support for the locally distributed agency (eliminating `:gen_server` mailbox bottleneck.)

### CODE REVIEW

**Review by facundokantox — COMMENTED** [review]
I know it is already merged. But I really do like this ^^
While my understanding of macros moves forwards, I feel I process it with a 8kb memory. And that's being generous

**Comment by am-kantox** [comment]
@facundokantox macros are very exciting, but this particular PR has exactly zero macros :) `quote`/`unquote` you see there is an [unquoted fragment](https://hexdocs.pm/elixir/Kernel.SpecialForms.html?#quote/2-binding-and-unquote-fragments) that is processed during the compilation stage.

**Comment by facundokantox** [comment]
Indeed. I got stuck some time following on `args = Macro.generate_arguments(arity, __MODULE__)` and `unquote_splicing(args)`

**Comment by am-kantox** [comment]
@facundokantox `Macro.generate_arguments/2` I need to delegate functions of different arities to another module. And `unquote_splicing/1` I need to _call_ it.

**Pull request merged**
